//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.resources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Games.
        /// </summary>
        internal static string ACTIVE_GAMES {
            get {
                return ResourceManager.GetString("ACTIVE_GAMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string ADD {
            get {
                return ResourceManager.GetString("ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatchFinder.
        /// </summary>
        internal static string APPLICATION_NAME {
            get {
                return ResourceManager.GetString("APPLICATION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attacker Unique Spawn.
        /// </summary>
        internal static string ATTACKER_UNIQUE_SPAWN {
            get {
                return ResourceManager.GetString("ATTACKER_UNIQUE_SPAWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bomb.
        /// </summary>
        internal static string BOMB {
            get {
                return ResourceManager.GetString("BOMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenger.
        /// </summary>
        internal static string CHALLENGER {
            get {
                return ResourceManager.GetString("CHALLENGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenges Accepted.
        /// </summary>
        internal static string CHALLENGES_ACCEPTED {
            get {
                return ResourceManager.GetString("CHALLENGES_ACCEPTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenges Taken.
        /// </summary>
        internal static string CHALLENGES_TAKEN {
            get {
                return ResourceManager.GetString("CHALLENGES_TAKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string CHANGE {
            get {
                return ResourceManager.GetString("CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Your Password.
        /// </summary>
        internal static string CHANGE_YOUR_PASSWORD {
            get {
                return ResourceManager.GetString("CHANGE_YOUR_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string CREATE {
            get {
                return ResourceManager.GetString("CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Game.
        /// </summary>
        internal static string CREATE_A_GAME {
            get {
                return ResourceManager.GetString("CREATE_A_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        internal static string CREATOR {
            get {
                return ResourceManager.GetString("CREATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Handicap.
        /// </summary>
        internal static string DAMAGE_HANDICAP {
            get {
                return ResourceManager.GetString("DAMAGE_HANDICAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string DAY {
            get {
                return ResourceManager.GetString("DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Death Replay.
        /// </summary>
        internal static string DEATH_REPLAY {
            get {
                return ResourceManager.GetString("DEATH_REPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Logins.
        /// </summary>
        internal static string EXTERNAL_LOGINS {
            get {
                return ResourceManager.GetString("EXTERNAL_LOGINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly Fire Damage.
        /// </summary>
        internal static string FRIENDLY_FIRE_DAMAGE {
            get {
                return ResourceManager.GetString("FRIENDLY_FIRE_DAMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        internal static string GAMES {
            get {
                return ResourceManager.GetString("GAMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games Abandoned.
        /// </summary>
        internal static string GAMES_ABANDONED {
            get {
                return ResourceManager.GetString("GAMES_ABANDONED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games Created.
        /// </summary>
        internal static string GAMES_CREATED {
            get {
                return ResourceManager.GetString("GAMES_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games Played.
        /// </summary>
        internal static string GAMES_PLAYED {
            get {
                return ResourceManager.GetString("GAMES_PLAYED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Details.
        /// </summary>
        internal static string GAME_DETAILS {
            get {
                return ResourceManager.GetString("GAME_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Mode.
        /// </summary>
        internal static string GAME_MODE {
            get {
                return ResourceManager.GetString("GAME_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Settings.
        /// </summary>
        internal static string GAME_SETTINGS {
            get {
                return ResourceManager.GetString("GAME_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HOME {
            get {
                return ResourceManager.GetString("HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostage.
        /// </summary>
        internal static string HOSTAGE {
            get {
                return ResourceManager.GetString("HOSTAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUD Settings.
        /// </summary>
        internal static string HUD_SETTINGS {
            get {
                return ResourceManager.GetString("HUD_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injured Health.
        /// </summary>
        internal static string INJURED_HEALTH {
            get {
                return ResourceManager.GetString("INJURED_HEALTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Game.
        /// </summary>
        internal static string JOIN_GAME {
            get {
                return ResourceManager.GetString("JOIN_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lean.
        /// </summary>
        internal static string LEAN {
            get {
                return ResourceManager.GetString("LEAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        internal static string MANAGE {
            get {
                return ResourceManager.GetString("MANAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string MAP {
            get {
                return ResourceManager.GetString("MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Settings.
        /// </summary>
        internal static string MATCH_SETTINGS {
            get {
                return ResourceManager.GetString("MATCH_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        internal static string MODE {
            get {
                return ResourceManager.GetString("MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode Settings.
        /// </summary>
        internal static string MODE_SETTINGS {
            get {
                return ResourceManager.GetString("MODE_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Games.
        /// </summary>
        internal static string MY_GAMES {
            get {
                return ResourceManager.GetString("MY_GAMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Stats.
        /// </summary>
        internal static string MY_STATS {
            get {
                return ResourceManager.GetString("MY_STATS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night.
        /// </summary>
        internal static string NIGHT {
            get {
                return ResourceManager.GetString("NIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string NOT_APPLICABLE_ABBREVIATION {
            get {
                return ResourceManager.GetString("NOT_APPLICABLE_ABBREVIATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Rounds.
        /// </summary>
        internal static string NUMBER_OF_ROUNDS {
            get {
                return ResourceManager.GetString("NUMBER_OF_ROUNDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objective Rotation Parameter.
        /// </summary>
        internal static string OBJECTIVE_ROTATION_PARAMETER {
            get {
                return ResourceManager.GetString("OBJECTIVE_ROTATION_PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string OFF {
            get {
                return ResourceManager.GetString("OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string ON {
            get {
                return ResourceManager.GetString("ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        internal static string OR {
            get {
                return ResourceManager.GetString("OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overtime Role Change.
        /// </summary>
        internal static string OVERTIME_ROLE_CHANGE {
            get {
                return ResourceManager.GetString("OVERTIME_ROLE_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overtime Rounds.
        /// </summary>
        internal static string OVERTIME_ROUNDS {
            get {
                return ResourceManager.GetString("OVERTIME_ROUNDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overtime Score Difference.
        /// </summary>
        internal static string OVERTIME_SCORE_DIFFERENCE {
            get {
                return ResourceManager.GetString("OVERTIME_SCORE_DIFFERENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string PHONE_NUMBER {
            get {
                return ResourceManager.GetString("PHONE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform.
        /// </summary>
        internal static string PLATFORM {
            get {
                return ResourceManager.GetString("PLATFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        internal static string PLAYERS {
            get {
                return ResourceManager.GetString("PLAYERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players per Team.
        /// </summary>
        internal static string PLAYERS_PER_TEAM {
            get {
                return ResourceManager.GetString("PLAYERS_PER_TEAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playstation 4.
        /// </summary>
        internal static string PLAYSTATION4 {
            get {
                return ResourceManager.GetString("PLAYSTATION4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please allow one hour prior to a game&apos;s scheduled start time, and one hour after the scheduled start time before scheduling another game. This game conflicts with another..
        /// </summary>
        internal static string PLEASE_ALLOW_ONE_HOUR_PRIOR_TO_A_GAMES_SCHEDULED_START_AND_ONE_HOUR_AFTER_CURRENT_GAME_CONFLICTS {
            get {
                return ResourceManager.GetString("PLEASE_ALLOW_ONE_HOUR_PRIOR_TO_A_GAMES_SCHEDULED_START_AND_ONE_HOUR_AFTER_CURRENT" +
                        "_GAME_CONFLICTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pro League.
        /// </summary>
        internal static string PRO_LEAGUE {
            get {
                return ResourceManager.GetString("PRO_LEAGUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate This Game.
        /// </summary>
        internal static string RATE_THIS_GAME {
            get {
                return ResourceManager.GetString("RATE_THIS_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reliability.
        /// </summary>
        internal static string RELIABILITY {
            get {
                return ResourceManager.GetString("RELIABILITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string REMOVE {
            get {
                return ResourceManager.GetString("REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Swap.
        /// </summary>
        internal static string ROLE_SWAP {
            get {
                return ResourceManager.GetString("ROLE_SWAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Set.
        /// </summary>
        internal static string RULE_SET {
            get {
                return ResourceManager.GetString("RULE_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Area.
        /// </summary>
        internal static string SECURE_AREA {
            get {
                return ResourceManager.GetString("SECURE_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        internal static string SET {
            get {
                return ResourceManager.GetString("SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string SIGN_UP {
            get {
                return ResourceManager.GetString("SIGN_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprint.
        /// </summary>
        internal static string SPRINT {
            get {
                return ResourceManager.GetString("SPRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string STANDARD {
            get {
                return ResourceManager.GetString("STANDARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time is limited to within six hours from now..
        /// </summary>
        internal static string START_TIME_IS_LIMITED_TO_WITHIN_SIX_HOURS_FROM_NOW {
            get {
                return ResourceManager.GetString("START_TIME_IS_LIMITED_TO_WITHIN_SIX_HOURS_FROM_NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tactical Realism.
        /// </summary>
        internal static string TACTICAL_REALISM {
            get {
                return ResourceManager.GetString("TACTICAL_REALISM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string TIME {
            get {
                return ResourceManager.GetString("TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time of Day.
        /// </summary>
        internal static string TIME_OF_DAY {
            get {
                return ResourceManager.GetString("TIME_OF_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string USERNAME {
            get {
                return ResourceManager.GetString("USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Image.
        /// </summary>
        internal static string USER_IMAGE {
            get {
                return ResourceManager.GetString("USER_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPlay.
        /// </summary>
        internal static string U_PLAY {
            get {
                return ResourceManager.GetString("U_PLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xbox One.
        /// </summary>
        internal static string XBOX_ONE {
            get {
                return ResourceManager.GetString("XBOX_ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string YES {
            get {
                return ResourceManager.GetString("YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not signed up for any matches.
        /// </summary>
        internal static string YOU_HAVE_NOT_SIGNED_UP_FOR_ANY_MATCHES {
            get {
                return ResourceManager.GetString("YOU_HAVE_NOT_SIGNED_UP_FOR_ANY_MATCHES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no active games..
        /// </summary>
        internal static string YOU_HAVE_NO_ACTIVE_GAMES {
            get {
                return ResourceManager.GetString("YOU_HAVE_NO_ACTIVE_GAMES", resourceCulture);
            }
        }
    }
}
